require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'StarterKit' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  target 'StarterKitTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'StarterKit-tvOS' do
  # Pods for PCRNStarterKit-tvOS

  target 'StarterKit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end