import './Welcome/Welcome.stories';
import './TextInput/TextInput.stories';
import './Icons/Icon.stories'
import "./Image/Image.stories"
import "./Button/Button.stories"
import "./Carousel/DSCarousel.stories"
import "./SelectInput/SelectInput.stories"
import "./Hr/Hr.stories"
import "./P/P.stories"
import "./Modal/Modal.stories"
import "./AutoComplete/AutoComplete.stories"
import "./DatePicker/DatePicker.stories"